export const groceries=[
    {
        id:1,
        image:"https://m.media-amazon.com/images/I/81J0rsL5EKL._AC_SY200_.jpg"
    }
    ,
    {
        id:2,
        image:"https://m.media-amazon.com/images/I/816ERSjWE-L._AC_SY200_.jpg"
    }
    ,
    {
        id:3,
        image:"https://m.media-amazon.com/images/I/61eG-b39JBL._AC_SY200_.jpg"
    }
    ,
    {
        id:4,
        image:"https://m.media-amazon.com/images/I/91VFuToiaGL._AC_SY200_.jpg"
    }
    ,
    {
        id:5,
        image:"https://m.media-amazon.com/images/I/61yR7yohv5L._AC_SY200_.jpg"
    }
    ,
    {
        id:6,
        image:"https://m.media-amazon.com/images/I/41jofqOlxNL._AC_SY200_.jpg"
    }
    ,
    {
        id:7,
        image:"https://m.media-amazon.com/images/I/61VF37h4r3L._AC_SY200_.jpg"
    }
    ,
    {
        id:8,
        image:"https://m.media-amazon.com/images/I/814rn5FmmDL._AC_SY200_.jpg"
    }
    ,
    {
        id:9,
        image:"https://m.media-amazon.com/images/I/31Qzm1jiChL._AC_SY200_.jpg"
    }
    ,
    {
        id:10,
        image:"https://m.media-amazon.com/images/I/71TwKynH41S._AC_SY200_.jpg"
    }
    ,
    {
        id:11,
        image:"https://m.media-amazon.com/images/I/61YFAQwdsJL._AC_SY200_.jpg"
    }
    ,
    {
        id:12,
        image:"https://m.media-amazon.com/images/I/817LK5nsRdL._AC_SY200_.jpg"
    }
    ,
    {
        id:13,
        image:"https://m.media-amazon.com/images/I/817LK5nsRdL._AC_SY200_.jpg"
    }
    ,
    {
        id:14,
        image:"https://m.media-amazon.com/images/I/81FvzMnYs6L._AC_SY200_.jpg"
    }
    ,
    {
        id:15,
        image:"https://m.media-amazon.com/images/I/912uVa0xA8L._AC_SY200_.jpg"
    }
]