export const shope=[
    {
        id:1,
        image:"https://m.media-amazon.com/images/I/610T5-u8ZRL._AC_SY200_.jpg"
    }
    ,
    {
        id:2,
        image:"https://m.media-amazon.com/images/I/61-xhMpd8iL._AC_SY200_.jpg"
    }
    ,
    {
        id:3,
        image:"https://m.media-amazon.com/images/I/711Bx2LM40L._AC_SY200_.jpg"
    }
    ,
    {
        id:4,
        image:"https://m.media-amazon.com/images/I/61Qf2R3vatL._AC_SY200_.jpg"
    }
    ,
    {
        id:5,
        image:"https://m.media-amazon.com/images/I/51n+u1do49L._AC_SY200_.jpg"
    }
    ,
    {
        id:6,
        image:"https://m.media-amazon.com/images/I/910CRhb-LIL._AC_SY200_.jpg"
    }
    ,
    {
        id:7,
        image:"https://m.media-amazon.com/images/I/81N11bYhzfL._AC_SY200_.jpg"
    } ,
    {
        id:8,
        image:"https://m.media-amazon.com/images/I/71yUxolgkJL._AC_SY200_.jpg"
    }
    ,
    {
        id:9,
        image:"https://m.media-amazon.com/images/I/71MrcMi43oS._AC_SY200_.jpg"
    }
    ,
    {
        id:10,
        image:"https://m.media-amazon.com/images/I/61+cJ-tGjoL._AC_SY200_.jpg"
    } ,
    {
        id:12,
        image:"https://m.media-amazon.com/images/I/71mMkRMJxJL._AC_SY200_.jpg"
    }
    ,
    {
        id:13,
        image:"https://m.media-amazon.com/images/I/61EQcXFEjNL._AC_SY200_.jpg"
    }
    ,
    {
        id:14,
        image:"https://m.media-amazon.com/images/I/71ObgdgauGL._AC_SY200_.jpg"
    }
    ,
    {
        id:15,
        image:"https://m.media-amazon.com/images/I/71xiclojEeL._AC_SY200_.jpg"
    }
    ,
    {
        id:16,
        image:"https://m.media-amazon.com/images/I/6153FimJaaL._AC_SY200_.jpg"
    }
    ,
    {
        id:17,
        image:"https://m.media-amazon.com/images/I/71KA8EZ-rFL._AC_SY200_.jpg"
    } ,
    {
        id:18,
        image:"https://m.media-amazon.com/images/I/61FoVxgS+lL._AC_SY200_.jpg"
    }
]