export const skin =[
    {
        id:1,
        image:"https://m.media-amazon.com/images/I/71CWj2FksWL._AC_SY200_.jpg"
    }
    ,
    {
        id:2,
        image:"https://m.media-amazon.com/images/I/9171KBwW+YL._AC_SY200_.jpg"
    }
    ,
    {
        id:3,
        image:"https://m.media-amazon.com/images/I/712z2r46EtL._AC_SY200_.jpg"
    }
    ,
    {
        id:4,
        image:"https://m.media-amazon.com/images/I/712z2r46EtL._AC_SY200_.jpg"
    }
    ,
    {
        id:5,
        image:"https://m.media-amazon.com/images/I/610HHXZAV3L._AC_SY200_.jpg"
    }
    ,
    {
        id:6,
        image:"https://m.media-amazon.com/images/I/51YjbgkMO7L._AC_SY200_.jpg"
    }
    ,
    {
        id:7,
        image:"https://m.media-amazon.com/images/I/71FHep6O1QL._AC_SY200_.jpg"
    }
    ,
    {
        id:8,
        image:"https://m.media-amazon.com/images/I/71-OJ4Dg3CL._AC_SY200_.jpg"
    }
    ,
    {
        id:9,
        image:"https://m.media-amazon.com/images/I/71r2Dee68BS._AC_SY200_.jpg"
    }
    ,
    {
        id:10,
        image:"https://m.media-amazon.com/images/I/61Wf5NHdbVL._AC_SY200_.jpg"
    }
    ,
    {
        id:11,
        image:"https://m.media-amazon.com/images/I/71H3ym27WEL._AC_SY200_.jpg"
    }
    ,
    {
        id:12,
        image:"https://m.media-amazon.com/images/I/61Ohkh0QNdL._AC_SY200_.jpg"
    }  ,
    {
        id:13,
        image:"https://m.media-amazon.com/images/I/71VnC+SetHL._AC_SY200_.jpg"
    }
    ,
    {
        id:14,
        image:"https://m.media-amazon.com/images/I/7162aaG7VZL._AC_SY200_.jpg"
    }
    ,
    {
        id:15,
        image:"https://m.media-amazon.com/images/I/51HBtBrp9aL._AC_SY200_.jpg"
    }

]