export const Women=[
    {
        id:1,
        image:"https://m.media-amazon.com/images/I/31Dv4PiE8eL._AC_SY200_.jpg",
    }
    ,
    {
        id:2,
        image:"https://m.media-amazon.com/images/I/41asxiEZAnL._AC_SY200_.jpg",
    }
    ,
    {
        id:3,
        image:"https://m.media-amazon.com/images/I/51YkL+O5zQL._AC_SY200_.jpg",
    }
    ,
    {
        id:4,
        image:"https://m.media-amazon.com/images/I/61VmOcTl-uL._AC_SY200_.jpg",
    }
    ,
    {
        id:5,
        image:"https://m.media-amazon.com/images/I/61Jcpqe0hcL._AC_SY200_.jpg",
    }
    ,
    {
        id:6,
        image:"https://m.media-amazon.com/images/I/61INH+-JS5L._AC_SY200_.jpg",
    }
    ,
    {
        id:7,
        image:"https://m.media-amazon.com/images/I/61NPBdDBojL._AC_SY200_.jpg",
    }
    ,
    {
        id:8,
        image:"https://m.media-amazon.com/images/I/61Rrexl5AeS._AC_SY200_.jpg",
    }
    ,
    {
        id:9,
        image:"https://m.media-amazon.com/images/I/51j9uND0DQL._AC_SY200_.jpg",
    }
    ,
    {
        id:10,
        image:"https://m.media-amazon.com/images/I/416HPjPH+YL._AC_SY200_.jpg",
    }
    ,
    {
        id:11,
        image:"https://m.media-amazon.com/images/I/71aC74bA6IL._AC_SY200_.jpg",
    }
    ,
    {
        id:12,
        image:"https://m.media-amazon.com/images/I/81lSpbHtVDL._AC_SY200_.jpg",
    }
    ,
    {
        id:13,
        image:"https://m.media-amazon.com/images/I/61ry6PloYfL._AC_SY200_.jpg",
    }
    ,
    {
        id:14,
        image:"https://m.media-amazon.com/images/I/61oRm0ABlbL._AC_SY200_.jpg",
    }
    ,
    {
        id:15,
        image:"https://m.media-amazon.com/images/I/71fEgl3UhrL._AC_SY200_.jpg",
    }
]